Update changing.py
To fix the error of "AttributeError: 'TracedPath' object has no attribute 'n_points_per_cubic_curve'" (because in the CONFIG dictionary of VMobject class, the n_points_per_cubic_curve dose not exist, and 'self.n_points_per_curve' is used now in 'set_anchors_and_handles' method instead)